[package]
name = "highwayhash"
description = "Bindings to AVX-2-optimized SIP-like hash functions"
version = "0.0.2"
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
repository = "https://github.com/vks/highwayhash-rs"
readme = "README.md"
license = "Apache-2.0"
build = "build.rs"
