[package]
name = "highwayhash"
description = "Bindings to optimized SIP-like hash functions"
version = "0.0.1"
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
repository = "https://github.com/vks/highwayhash-rs"
readme = "README.md"
license = "Apache-2.0 / MIT"
build = "build.rs"
